### ISSUE TITLE
Generating reports in multiple environments in single yaml pipeline

### ISSUE THREAD

**Issue by leyshon** [maciejmaciejewski/azure-pipelines-cucumber#19]
Hi, 

We've got a YAML pipeline where we've defined multiple deploy sections to different environments and then we run our tests in those environments and then we try to add the report for each environment to Azure DevOps using this extension. Currently we keep over-writing the report with later environments. Am I right to think that there's currently no way for the extension to handle this? If that is the case have you thought about implementing a tab per environment/stage?

**Comment by maciejmaciejewski** [comment]
Hello @leyshon 

Hello, I am aware of the issue but currently there is no way of doing this. It would require rewriting extensions to support react components. This is work in progress

**Comment by leyshon** [comment]
Thanks for confirming that

**Comment by sabdukerim** [comment]
Hi,

I read the question and the answer above. But just to be sure that this will address the same issue that I am facing, I would like to double check with this:
Currently, on azure devops release pipeline, we have 3 separate maven run tasks for 3 different browsers. But like Leyshon said above, the cucumber test result is being over-written into one. I tried to add 3 cucumber report tasks, hoping that there is a way to configure the path, so that corresponding test results would be generated separately and stored in 3 result folder. So you are saying, that would be impossible as well?
![Untitled](https://user-images.githubusercontent.com/65181059/95376924-d02f6c80-08af-11eb-90b5-a4bf9238b910.png)

**Comment by maciejmaciejewski** [comment]
The setup you pasted above won't work because report attachments indeed gets overwritten and you will be able to see only the last one. As I said this known issue and fix is work in progress, however I cannot give you any ETA at this point.
Since all your tests are in the same job you can try working it around - plugin takes path to directory containing json files as a parameter, all json files in given dir are then merged and uploaded as a report. You could use it as a consolidated report, I know it is not perfect, but that's the only solution that comes into my mind.

**Comment by sabdukerim** [comment]
thank you for your quick response. Now at lease I know that route is not an option. I will try what you suggested

**Comment by maciejmaciejewski** [comment]
Should be fixed by #45, new version has been released so please check it and close the issue if solution fits your needs.
