### ISSUE TITLE
Awesome plugin but failing  

### ISSUE THREAD

**Issue by DannMendis** [maciejmaciejewski/azure-pipelines-cucumber#9]
Thanks for the awesome plugin. I have configured the plugin but getting below error.  Is this mean NPM is mandatory?

My project is Java / Maven and project is already generating the cucumber.json and only need a way to upload and show in the Azure Devops Cucumber TAB

Anyway to use this without NPM?

`Starting: Publish Cucumber Report
==============================================================================
Task         : Publish Cucumber Report
Description  : Publish Cucumber Report
Version      : 1.0.4
Author       : Maciej Maciejewski
Help         : Replace with markdown to show in help
==============================================================================
##[warning]**Error: Unable to locate executable file: 'npm'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.**
Finishing: Publish Cucumber Report
`

**Comment by maciejmaciejewski** [comment]
Hello @DannMendis 

Thanks for reporting the issue.
I am using npm package that generates HTML output report from JSON which is then attached to the tab. Unfortunately this dependency could not have been embedded into the Azure DevOps extension due to package file limit set by Microsoft. Instead I build the package on the fly, but as you have noticed it requires node to be installed on the agent.

As a quick solution I can suggest you to install node on your agent using task.

As a better solution I will add installation to my task to avid such issues in the future. 

Regards,
Maciej

**Comment by maciejmaciejewski** [comment]
@DannMendis 
Please find YAML snippet for your convenience, just add it before the report task.

```
- task: NodeTool@0
  displayName: 'Install Node 12.x'
  inputs:
    versionSpec: 12.x
```

**Comment by DannMendis** [comment]
Much appreciated. I think about this as well. You can close this issue as I will get NPM / NODEJS installed in my Infra. This should fix the issue.

**Comment by DannMendis** [comment]
Confirming it working after NODE installation.

**Comment by maciejmaciejewski** [comment]
@DannMendis 
I am glad that it is working for you. I will add node as a agent prerequisite in the documentation. 
If you are satisfied please consider changing your rating on marketplace :)
